apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nexus-production
  namespace: nexus
spec:
  secretName: nexus-production-certificate
  issuerRef:
    name: letsencrypt-production
  dnsNames:
  - nexus.opeomotayo.net
    
