apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarqube-production
  namespace: sonarqube
spec:
  secretName: sonarqube-production-certificate
  issuerRef:
    name: letsencrypt-production
  dnsNames:
  - sonarqube.opeomotayo.net
    
